ansible_playbook: install.yml
extra_args:
git_branches_playbook: */master
git_branches_ansible_config: */master
git_url_ansible_config: https://github.com/TomonoriMatsumura/ansible-cfg.git
git_url_playbook: https://github.com/ansible-playbooks-centos7/exa.git
inventory_parameters: -i /home/ansible/.ansible_inventories/ansible-ci -l exa
ssh_private_key: centos7.pem
